"""empty message

Revision ID: 30c7d0c34c1f
Revises: 
Create Date: 2019-12-17 20:30:34.398564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c7d0c34c1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product', sa.Column('odoo_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Product', 'odoo_id')
    # ### end Alembic commands ###
